version: '3.8'
services:
  airflow-scheduler:
    image: apache/airflow:2.5.0
    restart: always
    container_name: airflow-scheduler
    depends_on:
      - airflow-webserver
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
    command: scheduler

  airflow-webserver:
    image: apache/airflow:2.5.0
    restart: always
    container_name: airflow-webserver
    ports:
      - "8080:8080"
    depends_on:
      - airflow-init
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
    command: webserver

  airflow-init:
    image: apache/airflow:2.5.0
    container_name: airflow-init
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
    command: bash -c "airflow db init && airflow users create \
      --username admin --password admin --firstname Air --lastname Flow --role Admin --email admin@example.com"